### ISSUE TITLE
GoLang 1.22 upgrade issues

### ISSUE THREAD

**Issue by sudheerit** [uber-go/cff#92]
After the golang 1.22 upgrade and latest cff installation, cff generation is failing with NilPointer Dereference.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x63e999e] goroutine 349 [running]:
go/types. (*Checker) .handleBailout (0x000162200, 0x000035c60)
/usr/local/go/src/go/types/check.go:367 +0x88
panic (10×6599a0, 06/86
/usr/local/go/src/runtime/panic.go:770 +0x132
go/types. (*StdSizes). Sizeof (0x0, {0x65e97f8, 0x67bcf20})
/us/local/go/src/go/types/sizes.go:228 +0x31e
go/types. (*Config). sizeof(...)
/usr/local/go/src/go/types/sizes.go:333
go/types. representableConst. func1(0x65e97f8?, 0x67bcf20?})
/us/local/go/src/go/types/const.go: 76 +0x9e
go/types representableConst ({0x65eb670, 0x67b0500}, 0x000162200, 0x67bcf20, 0x000034078)
/us/local/go/src/go/types/const.go:92 +0x192
go/types. (*Checker). representation(0x000162200, 0x0007cddcO, 0x67bcf20)
/us/local/go/src/go/types/const.go:256 +0x65
go/types. (*Checker). implicitTypeAndValue(0x000162200, 0xc0007cddcO, {0x6597f8, 0x67bcf20})
/us/local/go/src/go/types/expr.go: 375 +0x30d
go/types. (*Checker). convertUntyped (0xc000162200, 0xc0007cddcO, {0x65e97f8, 0x67bcf20})
/us/local/go/src/go/types/const.go: 289 +0x3f
go/types. (*Checker) -matchTypes (0x000162200, 0x0007cdd80, 0x0007cddcO)
/us/local/go/src/go/types/expr.go:926 +0x79
go/types. (*Checker). binary(0x000162200, 0x0007cdd80, {665eac80, Oxc0002fe7eO}, {0x65ea770, 0xc0003425a0}, {0x65ea7d0
/us/local/go/src/go/types/expr.go: 800 +0x166
go/types. (*Checker).exprInternal (0x000162200, 0x0, 0x0007dd80, {0x65ac80, 0x0002fe7eO}, {0x0, 0x0})
/us/local/go/src/go/types/expr.go: 1416 +0x206
go/types. (*Checker). rawExp(0x000162200, 0x0, 0x0007cdd80, {0x65eac80?, 0x0002fe70?, {0x0?, 0x07}, 0x0)
/us/local/go/src/go/types/expr.go: 979 +0x19e
go/types. (*Checker). expr(0x000162200, 0x65a060?, 0x0007cdd80, {0x65eac80?, 0x0002fe7e07})
/usr/local/go/src/go/types/expr.go:1513 +0x30
go/types. (*Checker). stmt(0x000162200, 0x0, {0x65eafe®, 0xc0007cce80})
/usr/local/go/src/go/types/stmt.go:570 +0x11f2
go/types. (*Checker).stmtList(0x000162200, 0x0, {0x000342840?, 0x0?, 0x077)
/us/local/go/src/go/types/stmt-go: 121 +0x85
go/types. (*Checker). funcBody (0x000162200, 0x6597f8?, {0x000286d8?, 0x67bd1002}, 0xc0007cda40, 0xc0002fe870, {0x07, 0
/us/local/go/src/go/types/stmt.go:41 +0x331
go/types. (*Checker). funcDecl. func1()
/us/local/go/src/go/types/decl.go: 852 +0x3a
go/types. (*Checker) -processDelayed (0xc000162200, 0x0)
/us/local/go/src/go/types/check. go: 467 +0x162
go/types. (*Checker).checkFiles(0x000162200, {0x0002a8270, 0x1, 0x1})
/us/local/go/src/go/types/check.go: 411 +0x1cc
go/types. *Checker). Files(...)
/us/local/go/src/go/types/ check.go: 372
golang.org/x/tools/go/packages. (*loader). loadPackage(0xc00014c000, 0xc0011bd7c0)
/Users/xyz/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:1001 +0x76f
golang. org/x/tools/go/packages. (*loader). LoadRecursive. func1()
/Users/xyz/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:838 +0x1a9
sync. (*0nce) . doS low(0x736e692209090a2c?, 0x226f672e74636570?) /usr/local/go/src/sync/once.go:74 +0xc2
sync. (*0nce) .Do (...)
/usr/local/go/src/sync/once.go: 65
golang.org/x/tools/go/packages. (*loader). loadRecursive(0x6f4764656c69706d?, 0x203a2273656c6946?)
/Users/xyz/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:826 +0x4a
golang.org/x/tools/go/packages. (*loader). loadRecursive. func1.1(0x642209090a2c226f?)
/Users/xyz/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:833 +0x26
created by golang.org/x/tools/go/packages. (*loader). loadRecursive.funcl in goroutine 342
/Users/xyz/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:832

**Comment by tchung1118** [comment]
Hello, thank you for reporting this issue. Would you mind posting a repro for this?
